## source the users bashrc if it exists
if [ -n "$BASH_VERSION" ] && [ -f "${HOME}/.bashrc" ]; then
  . "${HOME}/.bashrc"
fi

# if [ -d "${HOME}/bin" ] ; then
#   PATH="${HOME}/bin:${PATH}"
# fi
#export SHELLOPTS
set -o igncr
if [ -d "${HOME}/man" ]; then
  MANPATH="${HOME}/man:${MANPATH}"
fi
if [ -d "${HOME}/info" ]; then
  INFOPATH="${HOME}/info:${INFOPATH}"
fi

export myroot=/c/dfromrays8350 # will become /d/
export GRADLE_HOME=/c/Gradle/gradle-9.1.0
mypath=
mypath=$myroot/bin:$mypath
mypath=$GRADLE_HOME/bin:$mypath
export mypath
export PATH=$mypath:$PATH   
cd $myroot
#if [ -f /c/Users/ray/miniconda3/etc/profile.d/conda.sh ]; then . /c/Users/ray/miniconda3/etc/profile.d/conda.sh; fi

