alias egrep='egrep --color=none'
alias fgrep='fgrep --color=none'
alias grep='grep --color=none'
#alias ls='ls --color=none -F'
alias ls="ls -F"
alias h=history
alias more=less
alias gs='git status'
alias gd='git diff'
alias gpom='git push origin master'




