alias egrep='egrep --color=none'
alias fgrep='fgrep --color=none'
alias grep='grep --color=none'
#alias ls='ls --color=none -F'
alias ls="ls -F"
alias h=history
alias df="df -h"
alias more=less
alias gs='git status'
alias gd='git diff'
alias gd1="git diff --word-diff=color --word-diff-regex='[^[:space:]]+'"
alias gpom='git push origin master'




