## source the users bashrc if it exists
if [ -n "$BASH_VERSION" ] && [ -f "${HOME}/.bashrc" ]; then
  . "${HOME}/.bashrc"
fi

set -o igncr

#export SHELLOPTS

if [ -d "${HOME}/man" ]; then
  MANPATH="${HOME}/man:${MANPATH}"
fi
if [ -d "${HOME}/info" ]; then
  INFOPATH="${HOME}/info:${INFOPATH}"
fi

#cd $myroot

#if [ -f /c/Users/ray/miniconda3/etc/profile.d/conda.sh ]; then . /c/Users/ray/miniconda3/etc/profile.d/conda.sh; fi

